### ISSUE TITLE
Don't compile float in the attribute

### ISSUE THREAD

**Issue by YamiOdymel** [Talesoft/tale-jade#111]
tale-jade:

```
input.zoom.slider(type=range min=0.1 max=2 step=0.01)
```

rendered

```
<input class="zoom slider" type="range"<?php $__value = 0.1; if (!\Tale\Jade\Compiler\is_null_or_false($__value)) echo ' min='.\Tale\Jade\Compiler\build_value($__value, '"', true); unset($__value);?> max="2"<?php $__value = 0.01; if (!\Tale\Jade\Compiler\is_null_or_false($__value)) echo ' step='.\Tale\Jade\Compiler\build_value($__value, '"', true); unset($__value);?>>
```

expecting

```
<input class="zoom slider" type="range" min="0.1" max="2" step="0.02">
```

unless I quote them

```
input.zoom.slider(type=range min="0.1" max=2 step="0.01")
```

Is it possible?

**Comment by TorbenKoehn** [comment]
As soon as you don't use quotes, Tale Jade assumes it's an expression.

The new compiler already changed the way scalar vs. expression handling works (also enabling usage of PHP constants etc.), it may work there, but it will take a whole while until the new compiler gets released.

I will think about doing a quick fix for this in the current compiler.

Is there any reason why you need the output like that? Or do you want it just for the readability, or let's say, performance?

**Comment by YamiOdymel** [comment]
I did that is just because the readability, so if you already fixed it in the new compiler,

I think there's no need to fix it in the old compiler (because I can just add the quotes), 

and since you talked about the performance,

the current performance is kinda slow while loading the cache (it took 0.2s),

I might talk about it by opening a new issue, thanks for making a such great template engine :D

**Comment by TorbenKoehn** [comment]
Well, I actually didn't do too many tests on this, I basically know that the engine is quite fast and not too much memory consuming because of the patterns I used, but I'd love to have some performance tests and ideas to improve it, if needed.

I will make a quick-fix anyways I guess, since, as said, the new compiler will still take a while (probably like 2 months)

Loading from the cache should go relatively fast, but I'll wait for your new issue then :)
