### ISSUE TITLE
 Call to a member function append() on a non-object

### ISSUE THREAD

**Issue by YamiOdymel** [Talesoft/tale-jade#114]
# Error message

**Call to a member function append() on a non-object in vendor/talesoft/tale-jade/Parser.php on line 1025**

<img width="759" alt="2016-06-25 3 06 28" src="https://cloud.githubusercontent.com/assets/7308718/16355347/6bab4b76-3ae6-11e6-9076-ac15caf788fa.png">
# Tale-Jade

I was trying to separate my jade templates as a header, content, and a footer. (for PJAX use)

and here's my footer Tale-Jade:

```
                </div>
                <!-- / .pjax -->

            </section>
            <!-- / Content -->

        </main>
        <!-- / Main Container -->

    </div>
    <!-- / Outer -->

</section>

</body>
</html>
```
# Why I did this

What I did is render each template(header, content, footer),

and when I got the HTTP_X_PJAX header, I **send the content part only**,

if it's a normal request, **I send the whole rendered result**, it's very useful with PJAX

when use PJAX I can just replace the content without refreshing the whole page, and here's the example:

```
ob_start();
$TaleJade->render('header.jade');
$header = ob_get_clean();

ob_start();
$TaleJade->render('content.jade');
$content = ob_get_clean();

ob_start();
$TaleJade->render('footer.jade');
$footer = ob_get_clean();

if(isset($_SERVER['HTTP_X_PJAX']))
    echo json_encode(['html' => $content]);
else
    echo $header . $content . $footer;
```

**Comment by TorbenKoehn** [comment]
Don't use Tale Jade for HTML-only templates. Tale Jade is not made for partial templates like that, it needs include/extends to work correctly.

For this one, use normal .html-files.

Also, you don't need output buffering, `Renderer->render` returns a string

Do it like this:

``` php
$header = file_get_contents('header.html');

$content = $TaleJade->render('content.jade');

$footer = file_get_contents('footer.html');

if(isset($_SERVER['HTTP_X_PJAX']))
    echo json_encode(['html' => $content]);
else
    echo $header . $content . $footer;
```

**Comment by YamiOdymel** [comment]
Well, I have some mixins and variables in my `header` file, 

so it can't be a html file, what I have done is to add a `isset()` for `$this->currentParent` as the temporary solution, 

thanks for your suggestion btw :D

**Comment by TorbenKoehn** [comment]
The problem with this is, that it's just not how the lexer works (as in: There won't be a fix for it)

As soon as you start indenting wide and going narrower (a.k.a just writing close-tags and indenting those), you trigger the tree-structure of Jade.

What you might also do is just have them all in the first line

``` html
</div>
<!-- / .pjax -->

</section>
<!-- / Content -->

</main>
<!-- / Main Container -->

</div>
<!-- / Outer -->

</section>

</body>
</html>
```

It should work naturally for the header, if you indented it correctly. Only the open-tags that are closed in the footer would've to be written in HTML-style.

That'd be the technical correct way.

Taking your example, the first indentation the Lexer would recognize would be 16 Spaces and it would set that as `Level 1`, meaning to reach `Level 2` you'd require 17-32 spaces of indentation.

If you indent less from this point on (Everything under 15 spaces), you go down a level. You can go to `Level 0`, where you're in the `document`-Node of Jade (Or _No indentation_). Going a further level lower will result in an error (Which is quite wanted) since there's no element lower than the document node.

I realize dynamic includes would solve this problem and I'm still thinking about a cool solution.

**Comment by YamiOdymel** [comment]
wow, I didn't know that I could solve the problem by just removed the indents in my `footer` template,

I'm really enjoyed about how you explain how your template engine works.
