### ISSUE TITLE
Undefined property: Tale\Jade\Renderer::$_options

### ISSUE THREAD

**Issue by abarcenas29** [Talesoft/tale-jade#67]
I updated using composer resulting to this error. 

http://prntscr.com/aclcck

Here is how I declare it:

http://pastebin.com/iFttTPLt

**Comment by CagatayUlubay** [comment]
Try changing $_options to $options.

I am not sure, but this should work since some property names changed from $_NAME to $NAME

For further information look into this file: 

https://github.com/Talesoft/tale-config/blob/master/ConfigurableTrait.php

Please let me know if this helped.

**Comment by abarcenas29** [comment]
I will be editing the vendor file?

**Comment by CagatayUlubay** [comment]
Wait, before changing anything, do you use tale-config 0.2?

Try changing tale-config to 0.1, clear the composer cache and update again.

**Comment by TorbenKoehn** [comment]
This is an error I created by handling composer versions wrong in tale-config. I'm sorry.

You can fix it by fixing the version of `tale-config` that Tale Jade uses to `0.1`.
0.2 contains an update that changes the `ConfigurableTrait` private property `_config` to just `config`, which broke some accesses to that property in all configurable objects of Tale Jade.

It should normally be fixed by deleting the `vendor/` directory and the `composer.lock`, running `$ composer clear-cache`, making sure you use the latest Tale Jade version in your `composer.json` and run `$ composer update`

**Comment by TorbenKoehn** [comment]
@abarcenas29 Is this fixed for you?

**Comment by abarcenas29** [comment]
it did not. I deleted the vendor and the composer.lock as you mention and cleared the cache.  Oh, in the composer.json file it is written as `"talesoft/tale-jade": "*",`

Here is a screenshot of the installation http://prntscr.com/adrfms

**Comment by TorbenKoehn** [comment]
Yep, sorry, I've been dumb.

0.4.1 is now (correctly) 1.4.1.

Please update to 1.4.1.

Watch out for the [composer.json](https://github.com/Talesoft/tale-jade/blob/1.4.1/composer.json) of Tale Jade, it needs to have a fixed `"talesoft/tale-config": "0.1"`-requirement

**Comment by abarcenas29** [comment]
It's working now. Many thanks!
