### ISSUE TITLE
Error set attribute

### ISSUE THREAD

**Issue by est-by** [Talesoft/tale-jade#87]
- $pref_url="public/client/"
  html(lang='en')
  head
    block head
      //ERROR
      script(src="#{$pref_url}node_modules/systemjs/dist/system.src.js")
      //OK
      script(src=$pref_url."node_modules/systemjs/dist/system.src.js")

**Comment by TorbenKoehn** [comment]
Could you give some more explanation and also format your example so that I can see the actual problem?

Both compile correctly for me
http://sandbox.jade.talesoft.io/id-5730955f76d8f.html

**Comment by est-by** [comment]
This code indicates a problem
[bag.zip](https://github.com/Talesoft/tale-jade/files/258799/bag.zip)

**Comment by TorbenKoehn** [comment]
Alright, what you're running into is a simple escaping-problem.

Jade escapes everything by default. It doesn't help using `!{$pref_url}`, because the attribute value is an expression and gets escaped separately from the interpolation.

If you want it unescaped, use the following

``` jade
link(rel="stylesheet", href!="#{$url_root}app.css")
```

That works (I tested it [here](http://sandbox.jade.talesoft.io/id-5733034bbda6e.html))

Notice the `!=` to define the atttribute, which tells Jade: _Don't escape this attribute_.

Notice that this is **wanted** behaviour, since it protects your site from XSS-attacks from feeding user input into Jade files (automatically, by default).

**Comment by est-by** [comment]
Thank you! Everything is working! Thank you for the quick response.
