### ISSUE TITLE
cachePath

### ISSUE THREAD

**Issue by rauluranga** [Talesoft/tale-jade#92]
Hi!
I'm trying to change the cache path without any success, in the docs says that i must change the `cachePath` property, but the example source code updates the `cache_path` property, and finally in the source code merges from de`path` property of the `adapterOptions`object.

**Comment by rauluranga** [comment]
never mind i finally figured out
you should use:

``` php
$options = [
      'adapterOptions' => [
        'path' =>  ABSOLUTE_CACHE_PATH
     ]
];
$renderer = new Jade\Renderer($options);
```

**Comment by TorbenKoehn** [comment]
You can either pass `cache_path`, `cache_path` or `cache_dir` directly to the `Renderer`-Instance.

The option itself is set on a sub-key called `adapter_options` and it is called `path` only in that sub-option (Since e.g. the `Stream`-adapter doesn't need a path) which gets passed to the renderer adapter.

With 1.4.2 it was `cachePath` mapping to `adapterOptions`.`path`, now it is `cachePath`, `cache_path` or `cache_dir` mapping to `adapter_options`.`path`
